# Generated by Django 4.1.6 on 2023-03-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='brand',
            field=models.CharField(default='New', max_length=255),
        ),
    ]
