# Generated by Django 4.1.6 on 2023-03-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wallpaper_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
    ]
