# Generated by Django 4.2.2 on 2023-08-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_contact_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='resolution',
            field=models.CharField(default='1366x768', max_length=255),
        ),
    ]
